name: SkyblockPlugin
version: 1.0.0
main: me.lemurxd.skyblockplugin.Main
depend: [BentoBox, Vault]
api-version: 1.21
author: lemurxd
description: Basic bundle for SkyBlock servers.

commands:
  skyblockplugin:
    description: Główna komenda zarzadzania pluginem
    aliases: [sbp]
    usage: /sbp give <przedmiot> [gracz]
    permission: sbp.admin
    permission-message: "§cNie masz uprawnień do tej komendy!"
  drop:
    description: Otwiera menu zarządzania dropem
    usage: /drop
  orb:
    description: Daje graczowi orba
    usage: /orb

permissions:
  sbp.admin:
    description: Daje dostęp do komend admina (/sbp give)
    default: op